AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'vendor/**/*'
    - 'Guardfile'
    - 'db/migrate/*'
    - 'bin/*'
    - 'config/initializers/*'

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/*'
    - 'spec/interactors/*'
    - 'spec/jobs/*'
    - 'spec/controllers/api/v1/*'
    - 'db/schema.rb'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'app/jobs/unzip_file.rb'

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'app/channels/**/*'
    - 'config/application.rb'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '{}'
