---
language: ruby
cache: bundler
jdk:
  - openjdk8
addons:
  postgresql: 9.6
before_script:
  - psql -U postgres -f postgresql_setup.txt
  - RAILS_ENV=test bundle exec rails db:migrate
  - RAILS_ENV=test bundle exec rake sunspot:solr:start
  - sleep 30
script:
  - bundle exec rubocop
  - bundle exec rspec
