language: ruby
rbenv:
- 1.0.0
cache: bundler
jdk:
- openjdk8
env:
  matrix:
  - DB=postgresql
  # CodeCoverage ID
  - secure: 15127af958e813e8b942059eca33070b9223e376ef29ac4b670f4114ecab2099
script:
- bundle exec rspec
before_script:
- psql -U postgres -f postgresql_setup.txt
- RAILS_ENV=test bundle exec rails db:migrate
- RAILS_ENV=test bundle exec rake sunspot:solr:start
  # Need to sleep to let solr launch
- sleep 30
  # CodeCoverage report
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
