---
development:
  solr:
    hostname: localhost
    port: 8992
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8991
    log_level: WARNING
    path: /solr/test
