sandbox:
  solr:
    hostname: localhost
    port: 8994
    log_level: OFF
    path: /solr/sandbox
    memory: 2G

production:
  solr:
    hostname: localhost
    port: 8993
    log_level: WARNING
    path: /solr/production
    memory: 8G

development:
  solr:
    hostname: localhost
    port: 8992
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8991
    log_level: WARNING
    path: /solr/test
